export type { Product, ProductSegment, ProductSpec } from './product-types';
export { productSegments } from './product-types';
import type { Product } from './product-types';

export const products: Product[] = [
  {
    slug: 'split-muro-inverter-r32',
    title: 'Split Muro Inverter R32',
    brand: 'CLARK',
    segment: 'Residencial',
    family: 'Split muro',
    technology: 'Inverter',
    refrigerant: 'R32',
    capacity: '9.000 a 36.000 BTU/h',
    image: '/images/catalog/split-muro-inverter-r32-v2.webp',
    gallery: ['/images/catalog/split-muro-inverter-r32-v2.webp'],
    description: 'Línea frío/calor de alta eficiencia con control remoto y Wi-Fi incorporado en las series documentadas.',
    features: ['Wi-Fi incorporado', 'Modo Sleep', 'Descongelado inteligente', 'Temporizador'],
    models: ['ICRE-09HRE1', 'ICRE-12HRE1', 'ICRE-18HRE1', 'ICRE-24HRE1', 'ICRE-36HRE1'],
    specs: [
      { label: 'Alimentación', value: '220–240 V / 50 Hz' },
      { label: 'EER', value: '3,21–3,22 W/W' },
      { label: 'COP', value: '3,61–3,62 W/W' },
      { label: 'Distancia máxima', value: '25 m entre unidades' },
    ],
    datasheet: '/fichas/split-muro-inverter-r32.pdf',
    note: 'La capacidad definitiva se confirma mediante cálculo de carga térmica.',
  },
  {
    slug: 'split-muro-inverter-r410a',
    title: 'Split Muro Inverter R410A',
    brand: 'CLARK',
    segment: 'Residencial',
    family: 'Split muro',
    technology: 'Inverter',
    refrigerant: 'R410A',
    capacity: '9.000 a 24.000 BTU/h',
    image: '/images/catalog/split-muro-inverter-r32-v2.webp',
    gallery: ['/images/catalog/split-muro-inverter-r32-v2.webp'],
    description: 'Alternativa Inverter de generación R410A para proyectos o reposiciones compatibles, sujeta a disponibilidad.',
    features: ['Frío / calor', 'Auto Start', 'Operación silenciosa', 'Control remoto'],
    models: ['9.000 BTU/h', '12.000 BTU/h', '18.000 BTU/h', '24.000 BTU/h'],
    specs: [
      { label: 'Tecnología', value: 'Compresor Inverter' },
      { label: 'Refrigerante', value: 'R410A' },
      { label: 'Aplicación', value: 'Dormitorios, livings y oficinas' },
      { label: 'Disponibilidad', value: 'Confirmar antes de cotizar' },
    ],
    datasheet: '/fichas/split-muro-inverter-r410a.pdf',
    note: 'Línea documentada en material 2023; confirmar vigencia y stock con el equipo técnico.',
  },
  {
    slug: 'split-muro-convencional',
    title: 'Split Muro Convencional',
    brand: 'CLARK',
    segment: 'Residencial',
    family: 'Split muro',
    technology: 'On/Off',
    refrigerant: 'R410A',
    capacity: '9.000 a 24.000 BTU/h',
    image: '/images/catalog/split-muro-convencional-v2.webp',
    gallery: ['/images/catalog/split-muro-convencional-v2.webp'],
    description: 'Equipo frío/calor convencional disponible en cuatro capacidades para climatización de uso cotidiano.',
    features: ['Frío / calor', 'Auto Start', 'Modo Sleep', 'Temporizador'],
    models: ['CSA-09HRE1', 'CSA-12HRE1', 'CSA-18HRE1', 'CSA-24HRE1'],
    specs: [
      { label: 'Alimentación', value: '220–240 V / 50 Hz' },
      { label: 'EER', value: '3,21–3,22 W/W' },
      { label: 'COP', value: '3,61–3,71 W/W' },
      { label: 'Distancia máxima', value: '20–25 m según modelo' },
    ],
    datasheet: '/fichas/split-muro-convencional.pdf',
  },
  {
    slug: 'aire-de-ventana',
    title: 'Aire de Ventana',
    brand: 'CLARK',
    segment: 'Residencial',
    family: 'Ventana',
    technology: 'Compacto',
    refrigerant: 'Según modelo',
    capacity: 'Formato integrado',
    image: '/images/catalog/aire-ventana-v2.webp',
    gallery: ['/images/catalog/aire-ventana-v2.webp'],
    description: 'Equipo compacto que reúne evaporador y condensador en una sola unidad para instalaciones específicas.',
    features: ['Diseño compacto', 'Control frontal', 'Flujo orientable', 'Solución integral'],
    models: ['Configuración según disponibilidad'],
    specs: [
      { label: 'Instalación', value: 'En vano o muro acondicionado' },
      { label: 'Formato', value: 'Unidad integrada' },
      { label: 'Control', value: 'Panel frontal' },
      { label: 'Dimensionamiento', value: 'Según recinto y vano disponible' },
    ],
    note: 'La capacidad, refrigerante y alimentación se confirman según el modelo disponible.',
  },
  {
    slug: 'portatil-12000',
    title: 'Equipo Portátil 12.000 BTU',
    brand: 'CLARK',
    segment: 'Residencial',
    family: 'Portátil',
    technology: 'Compacto',
    refrigerant: 'R410A',
    capacity: '12.000 BTU/h',
    image: '/images/catalog/aire-portatil-v2.webp',
    gallery: ['/images/catalog/aire-portatil-v2.webp'],
    description: 'Solución desplazable frío/calor con deshumidificación, temporizador y modo nocturno de bajo ruido.',
    features: ['Frío / calor', 'Modo dormir', 'Indicador de agua', 'Auto Start'],
    models: ['Portátil 12.000 BTU/h'],
    specs: [
      { label: 'Refrigeración', value: '3.500 W' },
      { label: 'Calefacción', value: '3.000 W' },
      { label: 'Nivel de ruido', value: '52 dB(A)' },
      { label: 'Peso neto', value: '23 kg' },
    ],
    datasheet: '/fichas/portatil-12000.pdf',
  },
  {
    slug: 'portatil-14000',
    title: 'Equipo Portátil 14.000 BTU',
    brand: 'CLARK',
    segment: 'Residencial',
    family: 'Portátil',
    technology: 'Compacto',
    refrigerant: 'R410A',
    capacity: '14.000 BTU/h',
    image: '/images/catalog/aire-portatil-v2.webp',
    gallery: ['/images/catalog/aire-portatil-v2.webp'],
    description: 'Portátil frío/calor para recintos que requieren mayor capacidad sin una unidad mural fija.',
    features: ['Control remoto', 'Tres velocidades', 'Temporizador 24 h', 'Modo seco'],
    models: ['NPH-14H', 'EQ-PORTATIL14K'],
    specs: [
      { label: 'Refrigeración', value: '3,9 kW' },
      { label: 'Calefacción', value: '3,1 kW' },
      { label: 'Caudal de aire', value: '430 m³/h' },
      { label: 'Nivel de ruido', value: '54 dB(A)' },
    ],
    datasheet: '/fichas/portatil-14000.pdf',
  },
  {
    slug: 'cassette-inverter-r32',
    title: 'Cassette Inverter R32',
    brand: 'CLARK',
    segment: 'Comercial',
    family: 'Cassette',
    technology: 'Inverter',
    refrigerant: 'R32',
    capacity: '18.000 a 60.000 BTU/h',
    image: '/images/catalog/cassette-inverter.webp',
    gallery: ['/images/catalog/cassette-inverter.webp'],
    description: 'Distribución de aire en cuatro direcciones para oficinas, locales y recintos de mayor superficie.',
    features: ['Bomba de condensado', 'Control remoto', 'Auto Start', 'Descongelado inteligente'],
    models: ['INCA-18M1-R32', 'INCA-24M1-R32', 'INCA-36M1-R32', 'INCA-48T1-R32', 'INCA-60T1-R32'],
    specs: [
      { label: 'Capacidades', value: '18 / 24 / 36 / 48 / 60 mil BTU/h' },
      { label: 'Alimentación exterior', value: 'Monofásica o trifásica según modelo' },
      { label: 'Control remoto', value: 'Incluido' },
      { label: 'Termostato alámbrico', value: 'Opcional' },
    ],
    datasheet: '/fichas/cassette-inverter-r32.pdf',
  },
  {
    slug: 'cassette-convencional-tcl',
    title: 'Cassette Convencional TCL',
    brand: 'TCL',
    segment: 'Comercial',
    family: 'Cassette',
    technology: 'On/Off',
    refrigerant: 'R410A',
    capacity: '12.000 a 48.000 BTU/h',
    image: '/images/catalog/cassette-convencional-tcl-transparent.png',
    gallery: [
      '/images/catalog/cassette-convencional-tcl-transparent.png',
      '/images/catalog/gallery/cassette-convencional-exterior-transparent.png',
    ],
    description: 'Alternativa cassette convencional con fotografías reales de unidad interior y exterior.',
    features: ['Cuatro vías', 'Auto Start', 'Control remoto', 'Formato comercial'],
    models: ['12.000 BTU/h', '18.000 BTU/h', '24.000 BTU/h', '36.000 BTU/h', '48.000 BTU/h'],
    specs: [
      { label: 'Tecnología', value: 'On/Off' },
      { label: 'Configuración', value: 'Unidad interior, panel y unidad exterior' },
      { label: 'Aplicación', value: 'Oficinas, tiendas y recintos comerciales' },
      { label: 'Disponibilidad', value: 'Confirmar por proyecto' },
    ],
    datasheet: '/fichas/cassette-convencional.pdf',
  },
  {
    slug: 'ducto-inverter-r32',
    title: 'Ducto Inverter R32',
    brand: 'CLARK',
    segment: 'Comercial',
    family: 'Ducto',
    technology: 'Inverter',
    refrigerant: 'R32',
    capacity: '48.000 y 60.000 BTU/h',
    image: '/images/catalog/ducto-inverter.webp',
    gallery: ['/images/catalog/ducto-inverter.webp', '/images/catalog/gallery/ducto-angulo.webp', '/images/catalog/gallery/ducto-control.webp'],
    description: 'Línea industrial 2026 de unidad interior canalizable para climatización discreta mediante ductos.',
    features: ['Termostato alámbrico', 'Auto Start', 'Deshumidificación', 'Trifásico exterior'],
    models: ['INDU-48T2-R32', 'INDU-60T2-R32'],
    specs: [
      { label: 'Alimentación exterior', value: '380–415 V / 50 Hz / 3 fases' },
      { label: 'EER', value: '3,21 W/W' },
      { label: 'COP', value: '3,61 W/W' },
      { label: 'Longitud máxima', value: '60 m' },
    ],
    datasheet: '/fichas/ducto-inverter-r32.pdf',
    video: '/videos/ducto-clark.mp4',
  },
  {
    slug: 'ducto-inverter-r410a',
    title: 'Ducto Inverter R410A',
    brand: 'CLARK',
    segment: 'Comercial',
    family: 'Ducto',
    technology: 'Inverter',
    refrigerant: 'R410A',
    capacity: '18.000 a 60.000 BTU/h',
    image: '/images/catalog/ducto-inverter.webp',
    gallery: ['/images/catalog/ducto-inverter.webp', '/images/catalog/gallery/ducto-angulo.webp', '/images/catalog/gallery/ducto-control.webp'],
    description: 'Familia canalizable Inverter para proyectos que requieren una distribución centralizada y oculta.',
    features: ['Termostato', 'Auto Start', 'Deshumidificación', 'Cinco capacidades'],
    models: ['INCD-18HRE', 'INCD-24HRE', 'INCD-36HRE3', 'INCD-48HRE4', 'INCD-60HRTE4'],
    specs: [
      { label: 'Capacidades', value: '18 / 24 / 36 / 48 / 60 mil BTU/h' },
      { label: 'EER', value: '2,70–3,20 W/W' },
      { label: 'COP', value: '3,20–4,01 W/W' },
      { label: 'Longitud máxima', value: '30–50 m según modelo' },
    ],
    datasheet: '/fichas/ducto-inverter-r410a.pdf',
    note: 'Confirmar vigencia de esta línea R410A frente a la nueva serie industrial R32.',
  },
  {
    slug: 'ducto-on-off',
    title: 'Ducto On/Off',
    brand: 'CLARK',
    segment: 'Comercial',
    family: 'Ducto',
    technology: 'On/Off',
    refrigerant: 'R410A',
    capacity: '18.000 a 60.000 BTU/h',
    image: '/images/catalog/ducto-inverter.webp',
    gallery: ['/images/catalog/ducto-inverter.webp', '/images/catalog/gallery/ducto-angulo.webp'],
    description: 'Alternativa convencional para distribución de aire por ductos en proyectos comerciales.',
    features: ['Control alámbrico', 'Auto Start', 'Cinco capacidades', 'Unidad oculta'],
    models: ['18.000 BTU/h', '24.000 BTU/h', '36.000 BTU/h', '48.000 BTU/h', '60.000 BTU/h'],
    specs: [
      { label: 'Tecnología', value: 'On/Off' },
      { label: 'Aplicación', value: 'Comercial y proyectos por ductos' },
      { label: 'Control', value: 'Termostato alámbrico' },
      { label: 'Disponibilidad', value: 'Confirmar por proyecto' },
    ],
    datasheet: '/fichas/ducto-on-off.pdf',
  },
  {
    slug: 'cielo-piso-inverter-r32',
    title: 'Cielo Piso Inverter R32',
    brand: 'CLARK',
    segment: 'Comercial',
    family: 'Cielo piso',
    technology: 'Inverter',
    refrigerant: 'R32',
    capacity: '24.000 a 60.000 BTU/h',
    image: '/images/catalog/cielo-piso-inverter.webp',
    gallery: ['/images/catalog/cielo-piso-inverter.webp', '/images/catalog/gallery/cielo-piso-exterior.webp', '/images/catalog/gallery/cielo-piso-control.webp'],
    description: 'Unidad versátil para instalación en cielo o muro bajo, orientada a salones, tiendas y oficinas.',
    features: ['Control remoto', 'Bajo nivel de ruido', 'Deshumidificación', 'Auto Start'],
    models: ['INPC-24M1-R32', 'INPC-36M1-R32', 'INPC-48T1-R32', 'INPC-60T1-R32'],
    specs: [
      { label: 'Capacidades', value: '24 / 36 / 48 / 60 mil BTU/h' },
      { label: 'Alimentación exterior', value: 'Monofásica o trifásica según modelo' },
      { label: 'Control remoto', value: 'Incluido' },
      { label: 'Termostato alámbrico', value: 'Opcional' },
    ],
    datasheet: '/fichas/cielo-piso-inverter-r32.pdf',
    video: '/videos/cielo-piso-clark.mp4',
  },
  {
    slug: 'cielo-piso-convencional',
    title: 'Cielo Piso Convencional',
    brand: 'CLARK',
    segment: 'Comercial',
    family: 'Cielo piso',
    technology: 'On/Off',
    refrigerant: 'R410A',
    capacity: '24.000 a 60.000 BTU/h',
    image: '/images/catalog/cielo-piso-convencional.webp',
    gallery: ['/images/catalog/cielo-piso-convencional.webp', '/images/catalog/gallery/cielo-piso-control.webp'],
    description: 'Formato cielo piso convencional para recintos amplios y proyectos con requerimientos simples de control.',
    features: ['Frío / calor', 'Control remoto', 'Auto Start', 'Montaje versátil'],
    models: ['24.000 BTU/h', '36.000 BTU/h', '48.000 BTU/h', '60.000 BTU/h'],
    specs: [
      { label: 'Tecnología', value: 'On/Off' },
      { label: 'Instalación', value: 'Cielo o muro bajo' },
      { label: 'Aplicación', value: 'Locales, oficinas y salones' },
      { label: 'Disponibilidad', value: 'Confirmar por proyecto' },
    ],
    datasheet: '/fichas/cielo-piso-convencional.pdf',
  },
  {
    slug: 'cortina-de-aire',
    title: 'Cortina de Aire',
    brand: 'CLARK',
    segment: 'Comercial',
    family: 'Cortina de aire',
    technology: 'Ventilación',
    refrigerant: 'No aplica',
    capacity: '90, 120 y 150 cm',
    image: '/images/catalog/cortina-de-aire-transparent.png',
    gallery: ['/images/catalog/cortina-de-aire-transparent.png'],
    description: 'Barrera de aire para accesos comerciales con tránsito frecuente, apta para instalación sobre puertas.',
    features: ['Control remoto', 'Ventilador centrífugo', 'Fácil limpieza', 'Altura de 2,3 a 3 m'],
    models: ['CAC-090C2', 'CAC-120C2', 'CAC-150C2'],
    specs: [
      { label: 'Caudal alto', value: '1.220 / 1.710 / 2.230 m³/h' },
      { label: 'Nivel de ruido', value: '57 / 59 / 60 dB' },
      { label: 'Alimentación', value: '220 V / 50 Hz / 1 fase' },
      { label: 'Altura recomendada', value: '2,3–3,0 m' },
    ],
    datasheet: '/fichas/cortina-aire.pdf',
  },
  {
    slug: 'bomba-calor-daitsu-acs',
    title: 'Bomba de Calor Daitsu para ACS',
    brand: 'Daitsu',
    segment: 'Energía térmica',
    family: 'Agua caliente sanitaria',
    technology: 'Bomba de calor',
    refrigerant: 'Según modelo',
    capacity: 'Dimensionamiento por demanda',
    image: '/images/catalog/bomba-calor-daitsu-v2.webp',
    gallery: ['/images/catalog/bomba-calor-daitsu-v2.webp', '/images/catalog/gallery/bomba-calor-daitsu-ambiente.webp'],
    description: 'Equipo compacto para producir y acumular agua caliente sanitaria mediante tecnología de bomba de calor.',
    features: ['Acumulación integrada', 'Análisis de demanda', 'Integración hidráulica', 'Instalación profesional'],
    models: ['Modelo y volumen por confirmar'],
    specs: [
      { label: 'Aplicación', value: 'Agua caliente sanitaria' },
      { label: 'Configuración', value: 'Bomba de calor con acumulación' },
      { label: 'Dimensionamiento', value: 'Según consumo y número de usuarios' },
      { label: 'Ficha técnica', value: 'Solicitar según modelo cotizado' },
    ],
    note: 'La carpeta recibida no incluye ficha técnica Daitsu; modelo, volumen, COP y refrigerante se confirman en la cotización.',
  },
  {
    slug: 'bomba-calor-piscina',
    title: 'Bomba de Calor para Piscina',
    brand: 'CLARK',
    segment: 'Energía térmica',
    family: 'Climatización de piscinas',
    technology: 'Bomba de calor',
    refrigerant: 'Según modelo',
    capacity: 'Según volumen de agua',
    image: '/images/catalog/bomba-calor-piscina-v2.webp',
    gallery: ['/images/catalog/bomba-calor-piscina-v2.webp'],
    description: 'Solución para temperar piscinas, hot tubs y piscinas estructurales mediante bomba de calor.',
    features: ['Uso exterior', 'Control integrado', 'Dimensionamiento hidráulico', 'Evaluación técnica'],
    models: ['Capacidad según volumen y condiciones de uso'],
    specs: [
      { label: 'Aplicación', value: 'Piscinas y hot tubs' },
      { label: 'Selección', value: 'Según volumen, clima y temperatura objetivo' },
      { label: 'Instalación', value: 'Requiere evaluación hidráulica y eléctrica' },
      { label: 'Disponibilidad', value: 'Confirmar por proyecto' },
    ],
    datasheet: '/fichas/bomba-calor-piscina.pdf',
    datasheetLabel: 'Ver folleto',
  },
  {
    slug: 'bomba-de-condensado',
    title: 'Bombas de Condensado',
    brand: 'CLARK',
    segment: 'Accesorios',
    family: 'Drenaje',
    technology: 'Accesorio',
    refrigerant: 'No aplica',
    capacity: '18 y 36 L/h',
    image: '/images/catalog/bomba-condensado.webp',
    gallery: ['/images/catalog/bomba-condensado.webp', '/images/catalog/gallery/bomba-condensado-maxi.webp'],
    description: 'Evacuación auxiliar para instalaciones donde el drenaje gravitacional no resulta viable.',
    features: ['Mini Pump', 'Maxi Pump', 'Hasta 10 m recomendados', 'Estanque de 35 ml'],
    models: ['CBC-18', 'CBC-36'],
    specs: [
      { label: 'Caudal máximo', value: '18 o 36 L/h a 0 m' },
      { label: 'Succión máxima', value: '2 m' },
      { label: 'Altura recomendada', value: '10 m' },
      { label: 'Temperatura', value: '0–50 °C' },
    ],
    datasheet: '/fichas/bomba-condensado.pdf',
  },
  {
    slug: 'termostato-cableado',
    title: 'Termostato Cableado',
    brand: 'CLARK',
    segment: 'Accesorios',
    family: 'Control',
    technology: 'Control',
    refrigerant: 'No aplica',
    capacity: 'Para equipos compatibles',
    image: '/images/catalog/termostato.webp',
    gallery: ['/images/catalog/termostato.webp', '/images/catalog/gallery/termostato-frontal.webp'],
    description: 'Control de temperatura, modo y ventilación para sistemas comerciales compatibles.',
    features: ['Control de modo', 'Ajuste de temperatura', 'Velocidad de ventilación', 'Montaje mural'],
    models: ['Compatibilidad según equipo'],
    specs: [
      { label: 'Conexión', value: 'Cableada' },
      { label: 'Aplicación', value: 'Ducto, cassette y cielo piso compatibles' },
      { label: 'Programación', value: 'Según modelo de controlador' },
      { label: 'Compatibilidad', value: 'Confirmar antes de comprar' },
    ],
  },
  {
    slug: 'soportes-para-equipos',
    title: 'Soportes para Equipos',
    brand: 'CLARK',
    segment: 'Accesorios',
    family: 'Montaje',
    technology: 'Accesorio',
    refrigerant: 'No aplica',
    capacity: 'Series AF, AG y SF',
    image: '/images/catalog/soporte-af.webp',
    gallery: ['/images/catalog/gallery/soporte-af.webp', '/images/catalog/gallery/soporte-ag.webp', '/images/catalog/gallery/soporte-sf.webp'],
    description: 'Alternativas de soporte para el montaje seguro de unidades exteriores en distintos tipos de superficie.',
    features: ['Serie AF', 'Serie AG', 'Serie SF', 'Selección según carga'],
    models: ['AF', 'AG', 'SF'],
    specs: [
      { label: 'Uso', value: 'Montaje de unidad exterior' },
      { label: 'Selección', value: 'Según peso, superficie y exposición' },
      { label: 'Material', value: 'Metálico' },
      { label: 'Instalación', value: 'Con fijaciones compatibles con el soporte' },
    ],
  },
  {
    slug: 'refrigerantes-tecnicos',
    title: 'Refrigerantes Técnicos',
    brand: 'Multimarca',
    segment: 'Accesorios',
    family: 'Insumos técnicos',
    technology: 'Insumo',
    refrigerant: 'Según requerimiento',
    capacity: 'Bombonas de servicio',
    image: '/images/catalog/refrigerante-r134a.webp',
    gallery: ['/images/catalog/refrigerante-r134a.webp', '/images/catalog/gallery/refrigerante-celeste.webp', '/images/catalog/gallery/refrigerante-rosado.webp'],
    description: 'Insumos para servicio técnico, disponibles según tipo de refrigerante y compatibilidad del sistema.',
    features: ['Venta sujeta a disponibilidad', 'Tipo verificado antes de despacho', 'Uso técnico', 'Distintas presentaciones'],
    models: ['El tipo de gas se confirma antes de cotizar'],
    specs: [
      { label: 'Tipo', value: 'Según equipo y requerimiento técnico' },
      { label: 'Presentación', value: 'Bombona de servicio' },
      { label: 'Compatibilidad', value: 'Debe coincidir con la placa del equipo' },
      { label: 'Disponibilidad', value: 'Consultar' },
    ],
    note: 'El color de la bombona no se utiliza como identificación técnica del refrigerante.',
  },
];

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function productInquiry(product: string, model?: string) {
  const detail = model ? `, modelo ${model}` : '';
  return `https://wa.me/56996809677?text=${encodeURIComponent(
    `Hola CEROCLIMA, quisiera cotizar ${product}${detail}. ¿Me pueden orientar sobre disponibilidad, capacidad e instalación?`,
  )}`;
}
